### ISSUE TITLE
[BUG] RandomTP crashes Fabric Server

### ISSUE THREAD

**Issue by SigmaScorpii** [Picono435/RandomTP#6] opened 2021-08-09 11:56 UTC
**Describe the bug**
The Fabric server won't boot with RandomTP installed.

**To Reproduce**
Unsure.

**Expected behavior**
I expected the server to boot and the plugin to work.

**Desktop (please complete the following information):**
 - RandomTP version: 5.0.0
 - Minecraft Version: 1.17.1

**Additional context**
Log provided.
[2021-08-09-7.log](https://github.com/Picono435/RandomTP/files/6954293/2021-08-09-7.log)

**Comment by Picono435** [comment] 2021-08-09 12:00
Hello, could you please send me your RandomTP jar?

**Comment by SigmaScorpii** [comment] 2021-08-09 12:09
I added it inside of a zip file due to upload restrictions

[RandomTP-MC1.17.1-5.0.0-fabric.zip](https://github.com/Picono435/RandomTP/files/6954391/RandomTP-MC1.17.1-5.0.0-fabric.zip)

**Comment by Picono435** [comment] 2021-08-09 12:15
> I added it inside of a zip file due to upload restrictions
> 
> [RandomTP-MC1.17.1-5.0.0-fabric.zip](https://github.com/Picono435/RandomTP/files/6954391/RandomTP-MC1.17.1-5.0.0-fabric.zip)

I was not able to reproduce your issue, can you let me know your Fabric version?

**Comment by Picono435** [comment] 2021-08-09 12:28
For some reason I can't reproduce this issue, maybe it is an incompatibility with a mod. Can you tell me what OS are you running the server on? (Ubuntu 20.04, Windows 10, others...)

**Comment by SigmaScorpii** [comment] 2021-08-09 12:29
I'm unsure which version exactly we're using.
I've included both jar files of the server. The one we boot up is "Custom.jar".

I couldn't add the zip file in here, so threw it on Google Drive.
https://drive.google.com/file/d/1BlgAnCFHkrsPHi4-AXbg7p6_XS2CgfNq/view?usp=sharing

**Comment by SigmaScorpii** [comment] 2021-08-09 12:32
> For some reason I can't reproduce this issue, maybe it is an incompatibility with a mod. Can you tell me what OS are you running the server on? (Ubuntu 20.04, Windows 10, others...)

This is the information I have from the server hoster:
	Operating System: Linux (amd64) version 3.13.0-170-generic
	Java Version: 16.0.2, Oracle Corporation

**Comment by Picono435** [comment] 2021-08-09 13:01
Ok thank's for letting me know, I will investigate your issue.

**Comment by Picono435** [comment] 2021-08-10 17:00
So I tried to use your server jars and the latest RandomTP version for fabric and it worked just fine! This looks like an issue with another mod could you please add me into Discord (Picono435#2011).

**Comment by SigmaScorpii** [comment] 2021-08-10 17:03
I just added you on Discord, my name there is the same as on here.

**Comment by Picono435** [comment] 2021-08-10 21:25
Fixed in the latest versions of the mod.

**Closed as completed by Picono435** 2021-08-10 21:25 UTC
Labels: Bug
