### ISSUE TITLE
[1.16.3] /RTP not working for nonop's on the server even with permission

### ISSUE THREAD

**Issue by lulabyte** [Picono435/RandomTP#2] opened 2020-11-06 14:50 UTC
**Describe the bug**
I have set the config on the server to allow non-op's to /rtp, but it seems only I as the server op can use it. This seems like an anomaly and I'm sure I must be doing something wrong but I can't think of what.

**To Reproduce**
1. Install RTP mod, ensure config has been adjusted so non-op's can use the /rtp command.
2. Open Minecraft on the server as a non-op and attempt the /rtp command
3. Nothing happens :(
4. Server OP flexes her /rtp skills just fine

**Expected behavior**
Non server op's can use the /rtp command like the server op can

**Desktop (please complete the following information):**
 - RandomTP version: 1.16-4.1.2
 - Minecraft Version: 1.16.3
 - Machine Software: Windows

**Additional context**
Thanks for the mod! It's great!

**Comment by Picono435** [comment] 2020-11-06 17:20
Hello, thank you for contating me.

I am aware that currently the mod is having some issues in some cases with permissions.
 
These are some of the possible issues:

- You are using a plugin or mod like ForgeEssentials that changes the permission node, in this case use a debug option of the plugin/mod
- Your configuration is not well setted up, in this case please send us the config in order to we investigate

If none of these solved your issue please send a new message here.

**Comment by lulabyte** [comment] 2020-11-08 11:33
I don't have Forge essentials, but I'll have to see if any of my mods affect permissions. We do have a lot of mods.

Here is our config:

------------------------

[distance]
	#Minimum distance that you want to a person be teleported. [default: 1]
	#Range: > 1
	min_distance = 1
	# Max distance that you want to a person be teleported. (0 = world border size / 2) [default: auto]
	#Range: > 0
	max_distance = 0

[inter-dimensions-command]
	#Do you want to the command /rtpd be allowed? (This commands adds a inter-dimension RTP) [default: true]
	inter-dim = false
	#The dimensions whitelist (Works with namespaces:paths only, use-whitelist:true=whitelist use-whitelist:true=blacklist) [default: [minecraft:the_end], [twilight:dimension]]
	whitelist-dimension = ["minecraft:the_end", "twilight:dimension"]
	#Do you want to use the whitelist or blacklist dimension?  [default: false]
	use-whitelist = false

[permission]
	#If you want only op players or with the required permission node to execute the basic /rtp command. (Permission node: randomtp.command.basic) [default: true]
	only_op_basic = false
	#If you want only op players or with the required permission node to execute the inter dimension /rtpd command. (Permission node: randomtp.command.interdim) [default: true])
	only_op_dim = false

[others]
	#The amount of tries to find a safe location (original system) [-1 = infinite]
	max-tries = -1
	#If you want to use the original RTP system or the /spreadplayers system.
	use-original = true
	#How much cooldown do you want for the command (put 0 for none) [range: 0 ~ 1000, default: 0]
	#Range: > 0
	cooldown = 0

**Comment by Picono435** [comment] 2020-11-08 11:34
What is the permissions mod/plugin that you are using?

**Comment by lulabyte** [comment] 2020-11-08 15:53
naughty naughty Forge

**Comment by lulabyte** [comment] 2020-11-08 16:29
version 34.1.42

**Comment by Picono435** [comment] 2020-11-09 08:25
I will check if its a incompatibility with Forge 1.16.3, it might be the issue because the mod was made in 1.16.2-33.0.5, what will change very soon.

**Comment by lulabyte** [comment] 2020-11-09 14:38
thank you for your work!
I'm not entirely sure it's your fault now. I feel as if all of my mods' configs aren't translating even though the files are changed and saved.

**Comment by Picono435** [comment] 2020-12-23 13:52
Issue should be fixed now in last update.

**Comment by Alen-Roy** [comment] 2021-10-16 10:39
please help me! while iam using /rtp it works but non op players cant use that plugin how to give permission to use /rtp for them

**Comment by Picono435** [comment] 2021-10-16 10:46
This issue is now under investigation again, it will be confirmed and fixed asap.

**Comment by Alen-Roy** [comment] 2021-10-16 11:28
kk

**Comment by Picono435** [comment] 2021-10-30 12:11
Could you please let me know if you are using the latest mod version? And also what Minecraft version are you using?

**Comment by Picono435** [comment] 2022-12-16 15:53
This version is no longer supported. Sorry...

**Closed as completed by Picono435** 2022-12-16 15:53 UTC
Labels: Bug, Help wanted, Question
